require('set')
require('plugin')
require('themes')
require('keymap')
require("lsp")
-- require('plugin-config/coc');
require('plugin-config/autopairs')
require('plugin-config/nvim-tree')
require('plugin-config/bufferline')
require('plugin-config/lualine')
require('plugin-config/treesitter')
require('plugin-config/telescope')
require('plugin-config/comment')
require('plugin-config/hop')
require('plugin-config/leap')
require('plugin-config/color')
require('plugin-config/tmux')
require('plugin-config/toggleterm')
require('plugin-config/git')
require('plugin-config/translator')
require('plugin-config/yank')
require('plugin-config/session')
require('plugin-config/neoscroll')
-- require('plugin-config/onedark')
-- require('plugin-config/whichkey')
-- require('plugin-config/tressitter-textobject')

require('dap/dap-ui')
require('dap/dap-key')
require('dap/launch')
